# Generated by Django 4.2.6 on 2023-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
