# Generated by Django 5.0.1 on 2024-01-27 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notes',
            index=models.Index(fields=['creator', 'is_in_basket'], name='notes_notes_creator_116527_idx'),
        ),
    ]
