# Generated by Django 4.2.6 on 2023-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_text_alter_notes_title_notesbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_in_basket',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='NotesBasket',
        ),
    ]
