# Generated by Django 5.0.1 on 2024-01-28 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_communication', '0002_feedback_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating_stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
